# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nexcius.github.io
email: contact@nexcius.net
description: > 
  Share all the code!<br /> 
  Game Development, Programming and Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nexcius.net" # the base hostname & protocol for your site
twitter_username: nexcius
github_username:  nexcius
owner: Håvard Kindem

# Build settings
markdown: kramdown

encoding: utf-8
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

excerpt_separator: <!--more-->