# Site settings
title: Bad Vertex
#email: badvertex@gmail.com
description: Game Development, Programming and Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://badvertex.com" # the base hostname & protocol for your site
#twitter_username: nexcius
github_username:  badvertex
owner: Håvard Kindem

# Build settings
markdown: kramdown

encoding: utf-8
highlighter: rouge #pygments

kramdown:
  input: GFM
  hard_wrap: false

excerpt_separator: <!--more-->

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/page/:num/"